ci:
  autofix_commit_msg: "ci: pre-commit auto fixes"
  autoupdate_commit_msg: "ci: pre-commit auto update"
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.6
    hooks:
      - id: typos
        name: Check Typos
        args: []
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
