name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - '{{ cookiecutter.plugin }}/**'
      - 'cookiecutter.json'
      - 'hooks/**'
  push:
    paths:
      - '.github/workflows/test.yaml'
      - '{{ cookiecutter.plugin }}/**'
      - 'cookiecutter.json'
      - 'hooks/**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    env:
      PRE_COMMIT_HOME: .pre-commit
      PYTHONIOENCODING: utf-8
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v3.0.1
        with:
          path: ~/rsserpent-plugin-xxx/.pre-commit
          key: ${{ matrix.os }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - uses: actions/cache@v3.0.1
        with:
          path: ~/rsserpent-plugin-xxx/.venv
          key: ${{ matrix.os }}-${{ hashFiles('**/pyproject.toml') }}
      - name: "Setup Cookiecutter & Poetry"
        run: |
          pip install --upgrade pip
          pip install cookiecutter poetry
          poetry config virtualenvs.in-project true
      - name: "Generate Project from Template"
        run: cookiecutter -f --no-input gh:rsserpent/template -o ~
      - name: "Run pre-commit Hooks"
        run: |
          cd ~/rsserpent-plugin-xxx
          echo ".pre-commit" >> .gitignore
          git add --all
          poetry run pre-commit run --all-files
      - name: "Run Tests"
        run: |
          cd ~/rsserpent-plugin-xxx
          poetry run pytest --cov -n auto
